-- Phase 8 PR 1: additive Classroom tenancy and forced-RLS foundation.
--
-- NULL classroom_id is Personal Play. A Clerk Organization id is Class Play.
-- Apply with DATABASE_ADMIN_URL after migrations 0012 and 0013.

DO $roles$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_roles WHERE rolname = 'echo_maze_tenant_owner'
  ) THEN
    CREATE ROLE echo_maze_tenant_owner NOLOGIN;
  END IF;
END;
$roles$;

GRANT echo_maze_tenant_owner TO CURRENT_USER;
GRANT USAGE, CREATE ON SCHEMA public TO echo_maze_tenant_owner;

CREATE TABLE classrooms (
  id TEXT PRIMARY KEY CHECK (id ~ '^org_[A-Za-z0-9_-]{3,120}$'),
  name TEXT NOT NULL CHECK (char_length(name) BETWEEN 1 AND 120),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE classroom_memberships (
  classroom_id TEXT NOT NULL
    REFERENCES classrooms(id) ON DELETE CASCADE,
  clerk_user_id TEXT NOT NULL
    REFERENCES player_access(clerk_user_id) ON DELETE CASCADE
    CHECK (clerk_user_id ~ '^user_[A-Za-z0-9_-]{3,120}$'),
  clerk_membership_id TEXT NOT NULL UNIQUE
    CHECK (clerk_membership_id ~ '^orgmem_[A-Za-z0-9_-]{3,120}$'),
  role TEXT NOT NULL CHECK (role IN ('teacher', 'student')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (classroom_id, clerk_user_id)
);

CREATE INDEX classroom_memberships_user_idx
  ON classroom_memberships (clerk_user_id, classroom_id);

ALTER TABLE cloud_quest_progress
  ADD COLUMN record_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  ADD COLUMN classroom_id TEXT
    REFERENCES classrooms(id) ON DELETE CASCADE;
ALTER TABLE cloud_quest_progress
  DROP CONSTRAINT cloud_quest_progress_pkey,
  ALTER COLUMN record_id SET NOT NULL,
  ADD CONSTRAINT cloud_quest_progress_pkey PRIMARY KEY (record_id),
  ADD CONSTRAINT cloud_quest_progress_scope_unique
    UNIQUE NULLS NOT DISTINCT (clerk_user_id, classroom_id),
  ADD CONSTRAINT cloud_quest_progress_membership_fk
    FOREIGN KEY (classroom_id, clerk_user_id)
    REFERENCES classroom_memberships(classroom_id, clerk_user_id)
    ON DELETE CASCADE;
CREATE INDEX cloud_quest_progress_classroom_idx
  ON cloud_quest_progress (classroom_id, clerk_user_id);

ALTER TABLE learning_journals
  ADD COLUMN record_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  ADD COLUMN classroom_id TEXT
    REFERENCES classrooms(id) ON DELETE CASCADE;
ALTER TABLE learning_journals
  DROP CONSTRAINT learning_journals_pkey,
  ALTER COLUMN record_id SET NOT NULL,
  ADD CONSTRAINT learning_journals_pkey PRIMARY KEY (record_id),
  ADD CONSTRAINT learning_journals_scope_unique
    UNIQUE NULLS NOT DISTINCT (clerk_user_id, classroom_id),
  ADD CONSTRAINT learning_journals_membership_fk
    FOREIGN KEY (classroom_id, clerk_user_id)
    REFERENCES classroom_memberships(classroom_id, clerk_user_id)
    ON DELETE CASCADE;
CREATE INDEX learning_journals_classroom_idx
  ON learning_journals (classroom_id, clerk_user_id);

ALTER TABLE classrooms OWNER TO echo_maze_tenant_owner;
ALTER TABLE classroom_memberships OWNER TO echo_maze_tenant_owner;
ALTER TABLE cloud_quest_progress OWNER TO echo_maze_tenant_owner;
ALTER TABLE learning_journals OWNER TO echo_maze_tenant_owner;
ALTER SEQUENCE cloud_quest_progress_record_id_seq
  OWNER TO echo_maze_tenant_owner;
ALTER SEQUENCE learning_journals_record_id_seq
  OWNER TO echo_maze_tenant_owner;

REVOKE CREATE ON SCHEMA public FROM echo_maze_tenant_owner;
GRANT USAGE ON SCHEMA public TO echo_maze_tenant_owner;

ALTER TABLE classrooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE classrooms FORCE ROW LEVEL SECURITY;
ALTER TABLE classroom_memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE classroom_memberships FORCE ROW LEVEL SECURITY;
ALTER TABLE cloud_quest_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE cloud_quest_progress FORCE ROW LEVEL SECURITY;
ALTER TABLE learning_journals ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_journals FORCE ROW LEVEL SECURITY;

CREATE POLICY classroom_memberships_explorer_read
  ON classroom_memberships
  FOR SELECT
  TO echo_maze_runtime
  USING (
    clerk_user_id =
      NULLIF(current_setting('echo_maze.explorer_id', true), '')
  );

CREATE POLICY classrooms_selected_membership
  ON classrooms
  FOR SELECT
  TO echo_maze_runtime
  USING (
    id = NULLIF(current_setting('echo_maze.classroom_id', true), '')
    AND EXISTS (
      SELECT 1
      FROM classroom_memberships AS membership
      WHERE membership.classroom_id = classrooms.id
        AND membership.clerk_user_id =
          NULLIF(current_setting('echo_maze.explorer_id', true), '')
    )
  );

CREATE POLICY cloud_quest_progress_explorer_scope
  ON cloud_quest_progress
  FOR ALL
  TO echo_maze_runtime
  USING (
    clerk_user_id =
      NULLIF(current_setting('echo_maze.explorer_id', true), '')
    AND (
      (
        classroom_id IS NULL
        AND NULLIF(
          current_setting('echo_maze.classroom_id', true),
          ''
        ) IS NULL
      )
      OR
      (
        classroom_id =
          NULLIF(current_setting('echo_maze.classroom_id', true), '')
        AND EXISTS (
          SELECT 1
          FROM classroom_memberships AS membership
          WHERE membership.classroom_id =
            cloud_quest_progress.classroom_id
            AND membership.clerk_user_id =
              cloud_quest_progress.clerk_user_id
        )
      )
    )
  )
  WITH CHECK (
    clerk_user_id =
      NULLIF(current_setting('echo_maze.explorer_id', true), '')
    AND (
      (
        classroom_id IS NULL
        AND NULLIF(
          current_setting('echo_maze.classroom_id', true),
          ''
        ) IS NULL
      )
      OR
      (
        classroom_id =
          NULLIF(current_setting('echo_maze.classroom_id', true), '')
        AND EXISTS (
          SELECT 1
          FROM classroom_memberships AS membership
          WHERE membership.classroom_id =
            cloud_quest_progress.classroom_id
            AND membership.clerk_user_id =
              cloud_quest_progress.clerk_user_id
        )
      )
    )
  );

CREATE POLICY learning_journals_explorer_scope
  ON learning_journals
  FOR ALL
  TO echo_maze_runtime
  USING (
    clerk_user_id =
      NULLIF(current_setting('echo_maze.explorer_id', true), '')
    AND (
      (
        classroom_id IS NULL
        AND NULLIF(
          current_setting('echo_maze.classroom_id', true),
          ''
        ) IS NULL
      )
      OR
      (
        classroom_id =
          NULLIF(current_setting('echo_maze.classroom_id', true), '')
        AND EXISTS (
          SELECT 1
          FROM classroom_memberships AS membership
          WHERE membership.classroom_id = learning_journals.classroom_id
            AND membership.clerk_user_id = learning_journals.clerk_user_id
        )
      )
    )
  )
  WITH CHECK (
    clerk_user_id =
      NULLIF(current_setting('echo_maze.explorer_id', true), '')
    AND (
      (
        classroom_id IS NULL
        AND NULLIF(
          current_setting('echo_maze.classroom_id', true),
          ''
        ) IS NULL
      )
      OR
      (
        classroom_id =
          NULLIF(current_setting('echo_maze.classroom_id', true), '')
        AND EXISTS (
          SELECT 1
          FROM classroom_memberships AS membership
          WHERE membership.classroom_id = learning_journals.classroom_id
            AND membership.clerk_user_id = learning_journals.clerk_user_id
        )
      )
    )
  );

REVOKE ALL ON TABLE classrooms FROM PUBLIC, echo_maze_runtime;
REVOKE ALL ON TABLE classroom_memberships FROM PUBLIC, echo_maze_runtime;
REVOKE ALL ON TABLE cloud_quest_progress FROM PUBLIC, echo_maze_runtime;
REVOKE ALL ON TABLE learning_journals FROM PUBLIC, echo_maze_runtime;
REVOKE ALL ON SEQUENCE cloud_quest_progress_record_id_seq
  FROM PUBLIC, echo_maze_runtime;
REVOKE ALL ON SEQUENCE learning_journals_record_id_seq
  FROM PUBLIC, echo_maze_runtime;

GRANT SELECT ON TABLE classrooms, classroom_memberships
  TO echo_maze_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE
  ON TABLE cloud_quest_progress TO echo_maze_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE
  ON TABLE learning_journals TO echo_maze_runtime;
GRANT USAGE, SELECT ON SEQUENCE cloud_quest_progress_record_id_seq
  TO echo_maze_runtime;
GRANT USAGE, SELECT ON SEQUENCE learning_journals_record_id_seq
  TO echo_maze_runtime;
