/**
 * Daily Trail Constellation threshold policy.
 *
 * The numbers are the contract's, not an implementation detail: ADR 0033 fixes
 * 20 distinct contributors before a Daily publishes at all, 5 before any one
 * position becomes visible, and 10 new contributors before the published
 * snapshot advances. They live here rather than in SQL so each boundary can be
 * proved by test; the migration re-applies the same gates as defence in depth.
 *
 * @typedef {"quiet" | "glowing" | "bright"} ConstellationBand
 * @typedef {{
 *   kind: "cell" | "passage" | "pulse",
 *   x: number,
 *   y: number,
 *   contributorCount: number
 * }} ConstellationCounter
 * @typedef {{
 *   kind: "cell" | "passage" | "pulse",
 *   x: number,
 *   y: number,
 *   band: ConstellationBand
 * }} ConstellationMarker
 */

export const CONSTELLATION_PUBLISH_THRESHOLD = 20;
export const CONSTELLATION_MARKER_THRESHOLD = 5;
export const CONSTELLATION_BATCH_THRESHOLD = 10;

const DAY_MS = 24 * 60 * 60 * 1000;

/**
 * A Daily ends at the close of its UTC day and its aggregates live 48 hours
 * beyond that, so everything about it is gone at midnight UTC three days on.
 * The same instant is generated by the migration's `expires_at` column; this
 * is the read-path half of the guarantee.
 *
 * @param {string} dailyDate canonical UTC Daily key, `YYYY-MM-DD`
 */
export function constellationExpiresAt(dailyDate) {
  return new Date(Date.parse(`${dailyDate}T00:00:00.000Z`) + 3 * DAY_MS)
    .toISOString();
}

/**
 * @param {string} dailyDate
 * @param {Date} now
 */
export function isConstellationReadable(dailyDate, now) {
  return now.getTime() < Date.parse(constellationExpiresAt(dailyDate));
}

/**
 * A published snapshot only advances once a whole batch of new contributors
 * has arrived, so no single escape can be seen as a single-Explorer delta.
 *
 * @param {{ contributors: number, published: number }} counts
 */
export function shouldPublishBatch({ contributors, published }) {
  return contributors - published >= CONSTELLATION_BATCH_THRESHOLD;
}

/**
 * Turns published density counts into the three bands the surface may show.
 * Counts never leave this function: a marker carries its band and nothing
 * else, and a Daily that cannot show at least one marker is reported as still
 * forming rather than as a sparse map.
 *
 * @param {{
 *   publishedContributors: number,
 *   markers: ConstellationCounter[]
 * }} input
 * @returns {{ published: boolean, markers: ConstellationMarker[] }}
 */
export function projectConstellation({ publishedContributors, markers }) {
  const unpublished = { published: false, markers: [] };
  if (publishedContributors < CONSTELLATION_PUBLISH_THRESHOLD) {
    return unpublished;
  }
  const visible = markers.filter(
    (marker) => marker.contributorCount >= CONSTELLATION_MARKER_THRESHOLD
  );
  if (visible.length === 0) {
    return unpublished;
  }
  const peak = visible.reduce(
    (highest, marker) => Math.max(highest, marker.contributorCount),
    0
  );
  return {
    published: true,
    markers: visible.map((marker) => ({
      kind: marker.kind,
      x: marker.x,
      y: marker.y,
      band: constellationBand(marker.contributorCount, peak)
    }))
  };
}

/**
 * Thirds of the busiest visible marker. Relative rather than absolute because
 * an absolute scale would leak cohort size — the same corridor would read
 * Quiet on a small Daily and Bright on a large one, which is a count by
 * another name. ADR 0033 fixes the three band names but not their boundaries,
 * so the split is this implementation's choice.
 *
 * @param {number} count
 * @param {number} peak
 * @returns {ConstellationBand}
 */
export function constellationBand(count, peak) {
  if (count * 3 >= peak * 2) {
    return "bright";
  }
  if (count * 3 >= peak) {
    return "glowing";
  }
  return "quiet";
}
